# Sample YAML code for an AWS CloudFormation template
Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0c55b159cbfafe1f0
      SecurityGroups:
        - Ref: MySecurityGroup
      KeyName: MyKeyPair
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: My security group
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
  MySecretResource:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: MySecret
      Description: My secret value
      SecretString: '{"username": "my_username", "password": "my_password"}'